<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PartSaleOrder_Unit</name>
   <tag></tag>
   <elementGuidId>3faec72f-0c18-4d55-9882-9da33a9800df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tdtre4101m002-1-tdsls400.unit.c-48-lookup-widget</value>
   </webElementProperties>
</WebElementEntity>
