<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HomePage_RunProgram_</name>
   <tag></tag>
   <elementGuidId>82d7a28b-4f99-4c8a-85ab-3f4f2939fb92</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-overflowmenu-options-Options-run_program&quot;)/td[2]</value>
   </webElementProperties>
</WebElementEntity>
